# Generated by Django 5.1.6 on 2025-03-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Others', 'Others')], default='Others', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
